#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80 default_server/listen [::]:8080 default_server/g' /etc/nginx/sites-enabled/default
nginx -s stop 2>/dev/null || pkill nginx || true
sleep 1
/usr/sbin/nginx
