#!/usr/bin/env bash
# Installs UFW and configures it to allow only SSH (22), HTTP (80), and HTTPS (443)
apt-get update -y
apt-get install -y ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable
