#!/usr/bin/env bash
# Fixes Nginx to listen on port 80 instead of 8080
sed -i 's/listen 8080 default_server/listen 80 default_server/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080 default_server/listen [::]:80 default_server/g' /etc/nginx/sites-enabled/default
service nginx restart
