#!/usr/bin/env bash
# Configures nginx with a 301 redirect on /redirect_me
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
cat > /etc/nginx/sites-available/default << 'NGINX_CONF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    location / {
        try_files $uri $uri/ =404;
    }
}
NGINX_CONF
service nginx restart
