#!/usr/bin/env bash
# Configures nginx with a 301 redirect and custom 404 page
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i 's#location / {#location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {#' /etc/nginx/sites-enabled/default
sed -i '/server_name _/a error_page 404 /404.html;' /etc/nginx/sites-enabled/default
service nginx restart
